# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf58c67d71253b91d915f9a0cf253e821bdc63d5348c5cff1394204cb1c5eaad693f233d72aa228c8f25068958a16a432222b674aaf2e48005009be1d87f32bf

test:
  secret_key_base: 99d5b8095e737116ab7d9955b2a225d0a6bb4b53d31aeb51fb460ce14b9d76b873f051bc6d194ff3561a002197d043e3e419e777e65dfa4c9440d0c9ed48442f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
